#!/bin/sh -e
: ${cache_dir:=/tmp}

type sha1sum
type basename >&2
if type wget >&2; then
    download() { wget "$1" --output-document "$2"; }
else if type curl >&2; then
    download() { curl "$1" --output "$2"; }
fi fi

[ "$1" = "--no-cache" ] && no_cache=1 && shift

url="$1"

if [ -z "$url" ]; then
    echo "Usage: $0 URL\n" >&2
    exit 1
fi

[ -d "$cache_dir" ] || mkdir -p "$cache_dir"

hash=$(echo -n $url | sha1sum | cut -c1-8)
target="$cache_dir/$hash-$(basename $url)"

if [ "$no_cache" = "1" ] || [ ! -e $target ]; then
    download "$url" "${target}.tmp"
    mv "${target}.tmp" "$target"
fi

echo $target
