#!/bin/sh -ex

: ${container_name:=work}
: ${container_dir:=.vagga/$container_name}
: ${container_root:=.vagga/$container_name/root}
: ${nix_config:=default.nix}
: ${nix_attribute:=""}

type mkdir mv dirname readlink            # coreutils
type nix-instantiate nix-env nix-store    # nix
type rsync                                # rsync

profile=$container_dir/nix-profile

test -h $profile && unlink $profile
nix-env --profile $profile --install \
    --file "${nix_config}" --attr "${nix_attribute}"
closure=$(nix-store --query --requisites $profile)

mkdir -p $container_root/nix/store
rsync --recursive --links --perms --times --hard-links \
    --link-dest=$container_dir/root/nix/store \
    $closure $container_root/nix/store
rsync --recursive --links --perms --times \
    $profile/ $container_root

# few nix fixups
chmod -R u+w $container_root
mkdir -p $container_root/usr/bin
ln -sfn /bin/env $container_root/usr/bin/env
