name: Tests

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install musl-tools
        run: "sudo apt-get install musl-tools"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          default: true
    - uses: Swatinem/rust-cache@v1
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            tmp/cache
          key: vagga-cache-v1
      - run: |
          make
          ./vagga test
        env:
          UBUNTU_MIRROR: https://us.archive.ubuntu.com
